// Shared wire types for the agentsessions Session and Harness services.
//
// The Event message is used by BOTH the session log (Sessions.Exec / Replay) and the
// harness stream (Harness.Connect) — harness events become the log alongside host-owned records.
//
// The content model (Part) is aligned with A2A `Part` + MCP content for interop; the
// event/log model is native. Derived from the durable-log & replay contract §7 (record
// schema) and §8 (interop). See agentsessions-replay-determinism-contract.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package agentsessionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mediation controls how a tool call is executed / who enforces record-before-effect (§3).
type Mediation int32

const (
	Mediation_MEDIATION_UNSPECIFIED         Mediation = 0
	Mediation_MEDIATION_IN_HARNESS_REPORTED Mediation = 1 // harness runs it, reports for audit (cooperative WAL)
	Mediation_MEDIATION_CONTROLLER_MEDIATED Mediation = 2 // host/gateway executes (host-enforced WAL; trustless)
	Mediation_MEDIATION_REQUIRES_APPROVAL   Mediation = 3 // pause for human/policy approval
)

// Enum value maps for Mediation.
var (
	Mediation_name = map[int32]string{
		0: "MEDIATION_UNSPECIFIED",
		1: "MEDIATION_IN_HARNESS_REPORTED",
		2: "MEDIATION_CONTROLLER_MEDIATED",
		3: "MEDIATION_REQUIRES_APPROVAL",
	}
	Mediation_value = map[string]int32{
		"MEDIATION_UNSPECIFIED":         0,
		"MEDIATION_IN_HARNESS_REPORTED": 1,
		"MEDIATION_CONTROLLER_MEDIATED": 2,
		"MEDIATION_REQUIRES_APPROVAL":   3,
	}
)

func (x Mediation) Enum() *Mediation {
	p := new(Mediation)
	*p = x
	return p
}

func (x Mediation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mediation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Mediation) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Mediation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mediation.Descriptor instead.
func (Mediation) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type EventKind int32

const (
	EventKind_EVENT_KIND_UNSPECIFIED EventKind = 0
	EventKind_EVENT_INPUT            EventKind = 1 // a user/producer message
	EventKind_EVENT_MODEL_CALL       EventKind = 2 // model-call metadata (+ input_hash); output is an OUTPUT message
	EventKind_EVENT_OUTPUT           EventKind = 3 // a finalized assistant message; streaming deltas are transport, not logged
	EventKind_EVENT_TOOL_CALL        EventKind = 4
	EventKind_EVENT_TOOL_RESULT      EventKind = 5
	EventKind_EVENT_APPROVAL_REQUEST EventKind = 6
	EventKind_EVENT_APPROVAL_RESULT  EventKind = 7
	EventKind_EVENT_USAGE            EventKind = 8
	EventKind_EVENT_LIFECYCLE        EventKind = 9
	EventKind_EVENT_END              EventKind = 10
	EventKind_EVENT_ERROR            EventKind = 11
	EventKind_EVENT_EXECUTION_START  EventKind = 12 // host-owned config/cursor/input count, before inputs and harness effects
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0:  "EVENT_KIND_UNSPECIFIED",
		1:  "EVENT_INPUT",
		2:  "EVENT_MODEL_CALL",
		3:  "EVENT_OUTPUT",
		4:  "EVENT_TOOL_CALL",
		5:  "EVENT_TOOL_RESULT",
		6:  "EVENT_APPROVAL_REQUEST",
		7:  "EVENT_APPROVAL_RESULT",
		8:  "EVENT_USAGE",
		9:  "EVENT_LIFECYCLE",
		10: "EVENT_END",
		11: "EVENT_ERROR",
		12: "EVENT_EXECUTION_START",
	}
	EventKind_value = map[string]int32{
		"EVENT_KIND_UNSPECIFIED": 0,
		"EVENT_INPUT":            1,
		"EVENT_MODEL_CALL":       2,
		"EVENT_OUTPUT":           3,
		"EVENT_TOOL_CALL":        4,
		"EVENT_TOOL_RESULT":      5,
		"EVENT_APPROVAL_REQUEST": 6,
		"EVENT_APPROVAL_RESULT":  7,
		"EVENT_USAGE":            8,
		"EVENT_LIFECYCLE":        9,
		"EVENT_END":              10,
		"EVENT_ERROR":            11,
		"EVENT_EXECUTION_START":  12,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type Lifecycle_Kind int32

const (
	Lifecycle_LIFECYCLE_UNSPECIFIED Lifecycle_Kind = 0
	Lifecycle_LIFECYCLE_SUSPEND     Lifecycle_Kind = 1
	Lifecycle_LIFECYCLE_RESUME      Lifecycle_Kind = 2
	Lifecycle_LIFECYCLE_FORK        Lifecycle_Kind = 3
	Lifecycle_LIFECYCLE_BASELINE    Lifecycle_Kind = 4
	Lifecycle_LIFECYCLE_CANCEL      Lifecycle_Kind = 5
)

// Enum value maps for Lifecycle_Kind.
var (
	Lifecycle_Kind_name = map[int32]string{
		0: "LIFECYCLE_UNSPECIFIED",
		1: "LIFECYCLE_SUSPEND",
		2: "LIFECYCLE_RESUME",
		3: "LIFECYCLE_FORK",
		4: "LIFECYCLE_BASELINE",
		5: "LIFECYCLE_CANCEL",
	}
	Lifecycle_Kind_value = map[string]int32{
		"LIFECYCLE_UNSPECIFIED": 0,
		"LIFECYCLE_SUSPEND":     1,
		"LIFECYCLE_RESUME":      2,
		"LIFECYCLE_FORK":        3,
		"LIFECYCLE_BASELINE":    4,
		"LIFECYCLE_CANCEL":      5,
	}
)

func (x Lifecycle_Kind) Enum() *Lifecycle_Kind {
	p := new(Lifecycle_Kind)
	*p = x
	return p
}

func (x Lifecycle_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Lifecycle_Kind) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Lifecycle_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle_Kind.Descriptor instead.
func (Lifecycle_Kind) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17, 0}
}

// ResourceMetadata is carried by every top-level resource.
type ResourceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"` // tenant / namespace
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceMetadata) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ResourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceMetadata) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResourceMetadata) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ResourceMetadata) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// Part is one unit of message content. Text, file (inline or URI), structured data, or an
// opaque reasoning block. Large payloads are externalized by URI, never inlined (§8).
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*Part_Text
	//	*Part_File
	//	*Part_Data
	//	*Part_Reasoning
	Part          isPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Part) GetPart() isPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *Part) GetText() *TextPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Part) GetFile() *FilePart {
	if x != nil {
		if x, ok := x.Part.(*Part_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Part) GetData() *DataPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Part) GetReasoning() *ReasoningPart {
	if x != nil {
		if x, ok := x.Part.(*Part_Reasoning); ok {
			return x.Reasoning
		}
	}
	return nil
}

type isPart_Part interface {
	isPart_Part()
}

type Part_Text struct {
	Text *TextPart `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type Part_File struct {
	File *FilePart `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

type Part_Data struct {
	Data *DataPart `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

type Part_Reasoning struct {
	Reasoning *ReasoningPart `protobuf:"bytes,4,opt,name=reasoning,proto3,oneof"`
}

func (*Part_Text) isPart_Part() {}

func (*Part_File) isPart_Part() {}

func (*Part_Data) isPart_Part() {}

func (*Part_Reasoning) isPart_Part() {}

type TextPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextPart) Reset() {
	*x = TextPart{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextPart) ProtoMessage() {}

func (x *TextPart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextPart.ProtoReflect.Descriptor instead.
func (*TextPart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *TextPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// FilePart carries binary/media content inline or by reference (A2A file part; MCP
// resource_link / embedded resource). mime is an IANA media type.
type FilePart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mime  string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*FilePart_Bytes
	//	*FilePart_Uri
	Source        isFilePart_Source `protobuf_oneof:"source"`
	Name          string            `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`     // optional display name
	Digest        string            `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"` // content digest of the uri target (chain covers externalized bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePart) Reset() {
	*x = FilePart{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePart) ProtoMessage() {}

func (x *FilePart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePart.ProtoReflect.Descriptor instead.
func (*FilePart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *FilePart) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *FilePart) GetSource() isFilePart_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *FilePart) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Source.(*FilePart_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *FilePart) GetUri() string {
	if x != nil {
		if x, ok := x.Source.(*FilePart_Uri); ok {
			return x.Uri
		}
	}
	return ""
}

func (x *FilePart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilePart) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type isFilePart_Source interface {
	isFilePart_Source()
}

type FilePart_Bytes struct {
	Bytes []byte `protobuf:"bytes,2,opt,name=bytes,proto3,oneof"`
}

type FilePart_Uri struct {
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3,oneof"`
}

func (*FilePart_Bytes) isFilePart_Source() {}

func (*FilePart_Uri) isFilePart_Source() {}

// DataPart is structured JSON (A2A data part; MCP structuredContent).
type DataPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPart) Reset() {
	*x = DataPart{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPart) ProtoMessage() {}

func (x *DataPart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPart.ProtoReflect.Descriptor instead.
func (*DataPart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *DataPart) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

// ReasoningPart is an opaque, provider-tagged reasoning block that MUST be replayed
// verbatim to preserve reasoning continuity within a turn (I2). agentsessions never
// interprets `opaque` — all provider specifics live inside it. Verified across
// Anthropic/OpenAI/Gemini in the Track A reasoning-continuity spike: one part type, no
// per-provider sub-shapes, and no memory-snapshot edge (stateless verbatim replay).
type ReasoningPart struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`              // "anthropic" | "openai" | "google" — routing + validation
	ModelId  string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"` // model that produced it (cross-model resend case)
	// Types that are valid to be assigned to Opaque:
	//
	//	*ReasoningPart_OpaqueBytes
	//	*ReasoningPart_OpaqueUri
	Opaque        isReasoningPart_Opaque `protobuf_oneof:"opaque"`
	Summary       []*Part                `protobuf:"bytes,5,rep,name=summary,proto3" json:"summary,omitempty"`                                  // optional, NON-authoritative, compaction-droppable (may be multimodal)
	ItemId        string                 `protobuf:"bytes,6,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                      // optional provider id (e.g. OpenAI rs_...) for dedup/order
	Ordinal       int32                  `protobuf:"varint,7,opt,name=ordinal,proto3" json:"ordinal,omitempty"`                                 // position within the turn relative to text/tool parts
	ValidityScope string                 `protobuf:"bytes,8,opt,name=validity_scope,json=validityScope,proto3" json:"validity_scope,omitempty"` // = execution_id (turn); see replay contract §5
	OpaqueDigest  string                 `protobuf:"bytes,9,opt,name=opaque_digest,json=opaqueDigest,proto3" json:"opaque_digest,omitempty"`    // content digest of opaque_uri target (chain covers externalized bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningPart) Reset() {
	*x = ReasoningPart{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningPart) ProtoMessage() {}

func (x *ReasoningPart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningPart.ProtoReflect.Descriptor instead.
func (*ReasoningPart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *ReasoningPart) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReasoningPart) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ReasoningPart) GetOpaque() isReasoningPart_Opaque {
	if x != nil {
		return x.Opaque
	}
	return nil
}

func (x *ReasoningPart) GetOpaqueBytes() []byte {
	if x != nil {
		if x, ok := x.Opaque.(*ReasoningPart_OpaqueBytes); ok {
			return x.OpaqueBytes
		}
	}
	return nil
}

func (x *ReasoningPart) GetOpaqueUri() string {
	if x != nil {
		if x, ok := x.Opaque.(*ReasoningPart_OpaqueUri); ok {
			return x.OpaqueUri
		}
	}
	return ""
}

func (x *ReasoningPart) GetSummary() []*Part {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ReasoningPart) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ReasoningPart) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ReasoningPart) GetValidityScope() string {
	if x != nil {
		return x.ValidityScope
	}
	return ""
}

func (x *ReasoningPart) GetOpaqueDigest() string {
	if x != nil {
		return x.OpaqueDigest
	}
	return ""
}

type isReasoningPart_Opaque interface {
	isReasoningPart_Opaque()
}

type ReasoningPart_OpaqueBytes struct {
	OpaqueBytes []byte `protobuf:"bytes,3,opt,name=opaque_bytes,json=opaqueBytes,proto3,oneof"`
}

type ReasoningPart_OpaqueUri struct {
	OpaqueUri string `protobuf:"bytes,4,opt,name=opaque_uri,json=opaqueUri,proto3,oneof"` // externalized when large; retained for the turn's fork lifetime
}

func (*ReasoningPart_OpaqueBytes) isReasoningPart_Opaque() {}

func (*ReasoningPart_OpaqueUri) isReasoningPart_Opaque() {}

// Message is a role-tagged sequence of content parts (A2A Message = role + Part[]).
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // system, user, assistant, or tool
	Parts         []*Part                `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetParts() []*Part {
	if x != nil {
		return x.Parts
	}
	return nil
}

// IdentityRef is the bound agent principal. OIDC-neutral: an Entra Agent ID is one issuer;
// a SPIFFE ID or a GitHub App identity are others. Carried on every event.
type IdentityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Issuer        string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"` // session-scoped sub
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRef) Reset() {
	*x = IdentityRef{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRef) ProtoMessage() {}

func (x *IdentityRef) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRef.ProtoReflect.Descriptor instead.
func (*IdentityRef) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *IdentityRef) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *IdentityRef) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentityRef) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

// Origin is the neutral external context a session is tied to. Producer adapters
// (GitHub, Foundry, custom apps) fill it. Modeled on CloudEvents source/subject.
type Origin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Origin) Reset() {
	*x = Origin{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Origin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Origin) ProtoMessage() {}

func (x *Origin) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Origin.ProtoReflect.Descriptor instead.
func (*Origin) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *Origin) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Origin) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Origin) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Origin) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ModelCall is a model REQUEST emitted by the harness (EVENT_MODEL_CALL). The host records
// it with input_hash and answers via ControllerFrame.ModelResult (correlated by id). The
// completion (text + reasoning parts) is recorded separately as an EVENT_OUTPUT message.
// Under STATELESS_REPLAY the harness never calls a provider directly.
type ModelCall struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Model     string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Params    map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InputHash string                 `protobuf:"bytes,3,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"` // §7/§9.1: required for STATELESS_REPLAY so the I0 check can run
	Id        string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`                                // correlation id for the served ModelResult
	// messages is the request context the host needs to INVOKE the model on the live path. It is
	// wire-only: the host records the call with input_hash alone (messages stripped), since the
	// recorded form only needs the hash to re-check I0 on replay.
	Messages      []*Message `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCall) Reset() {
	*x = ModelCall{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCall) ProtoMessage() {}

func (x *ModelCall) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCall.ProtoReflect.Descriptor instead.
func (*ModelCall) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *ModelCall) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelCall) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ModelCall) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *ModelCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelCall) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	InputTokens     int64                  `protobuf:"varint,2,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens    int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Usage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

// ToolCall aligns with an MCP tool call (name + structured args).
type ToolCall struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tool           string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"` // tool name / MCP method
	Args           *structpb.Struct       `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	Mediation      Mediation              `protobuf:"varint,4,opt,name=mediation,proto3,enum=agentsessions.v1.Mediation" json:"mediation,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // §3/I3: dedups a retried side-effecting call tool-side
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolCall) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolCall) GetMediation() Mediation {
	if x != nil {
		return x.Mediation
	}
	return Mediation_MEDIATION_UNSPECIFIED
}

func (x *ToolCall) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	OutputUri     string                 `protobuf:"bytes,3,opt,name=output_uri,json=outputUri,proto3" json:"output_uri,omitempty"`          // externalized large output (MCP resource_link), else inline `output`
	OutputDigest  string                 `protobuf:"bytes,6,opt,name=output_digest,json=outputDigest,proto3" json:"output_digest,omitempty"` // content digest of output_uri target (chain covers externalized bytes)
	IsError       bool                   `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ToolResult) GetOutputUri() string {
	if x != nil {
		return x.OutputUri
	}
	return ""
}

func (x *ToolResult) GetOutputDigest() string {
	if x != nil {
		return x.OutputDigest
	}
	return ""
}

func (x *ToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Approval is modeled as durable log entries: an unresolved request, later resolved by a
// decision — so compute can suspend while awaiting a human/policy decision (§7).
type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *ApprovalRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ApprovalRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApprovalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResult) Reset() {
	*x = ApprovalResult{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResult) ProtoMessage() {}

func (x *ApprovalResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResult.ProtoReflect.Descriptor instead.
func (*ApprovalResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *ApprovalResult) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ApprovalResult) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // grpc status code
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type HarnessEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // COMPLETED | FAILED | CANCELED
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessEnd) Reset() {
	*x = HarnessEnd{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessEnd) ProtoMessage() {}

func (x *HarnessEnd) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessEnd.ProtoReflect.Descriptor instead.
func (*HarnessEnd) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *HarnessEnd) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HarnessEnd) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Lifecycle marks a compute/session transition in the log (§7). BASELINE is a replay /
// compaction checkpoint (§1).
type Lifecycle struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   Lifecycle_Kind         `protobuf:"varint,1,opt,name=kind,proto3,enum=agentsessions.v1.Lifecycle_Kind" json:"kind,omitempty"`
	Detail string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // e.g. "fork parent=<uid>@<seq>", baseline id
	// SnapshotRef captured on SUSPEND (§5.1), carried inline (mirroring the canonical api.SnapshotRef)
	// so it rides the tamper-evident chain with no side table and no cross-file message dependency.
	// This is distinct from the aspirational session-status message SnapshotRef in session.proto. A
	// filesystem-only backend sets only snapshot_local (the session handle to replay) with
	// snapshot_memory=false; a memory backend also sets snapshot_external_uri.
	SnapshotLocal       string `protobuf:"bytes,3,opt,name=snapshot_local,json=snapshotLocal,proto3" json:"snapshot_local,omitempty"`
	SnapshotExternalUri string `protobuf:"bytes,4,opt,name=snapshot_external_uri,json=snapshotExternalUri,proto3" json:"snapshot_external_uri,omitempty"`
	SnapshotMemory      bool   `protobuf:"varint,5,opt,name=snapshot_memory,json=snapshotMemory,proto3" json:"snapshot_memory,omitempty"`
	SnapshotSealed      bool   `protobuf:"varint,6,opt,name=snapshot_sealed,json=snapshotSealed,proto3" json:"snapshot_sealed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Lifecycle) Reset() {
	*x = Lifecycle{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lifecycle) ProtoMessage() {}

func (x *Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lifecycle.ProtoReflect.Descriptor instead.
func (*Lifecycle) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *Lifecycle) GetKind() Lifecycle_Kind {
	if x != nil {
		return x.Kind
	}
	return Lifecycle_LIFECYCLE_UNSPECIFIED
}

func (x *Lifecycle) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Lifecycle) GetSnapshotLocal() string {
	if x != nil {
		return x.SnapshotLocal
	}
	return ""
}

func (x *Lifecycle) GetSnapshotExternalUri() string {
	if x != nil {
		return x.SnapshotExternalUri
	}
	return ""
}

func (x *Lifecycle) GetSnapshotMemory() bool {
	if x != nil {
		return x.SnapshotMemory
	}
	return false
}

func (x *Lifecycle) GetSnapshotSealed() bool {
	if x != nil {
		return x.SnapshotSealed
	}
	return false
}

// ExecutionStart is host-owned invocation state, committed before the harness runs. The host
// emits it for non-default config/cursor or when there are no INPUT events to establish the turn.
// Logs without this event reconstruct with empty config and a zero cursor. Older discarded
// non-empty values cannot be recovered. Config is opaque: preserve bytes verbatim, never parse it.
type ExecutionStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	ResumeFromSeq int64                  `protobuf:"varint,2,opt,name=resume_from_seq,json=resumeFromSeq,proto3" json:"resume_from_seq,omitempty"` // harness cursor, distinct from the append CAS cursor
	// Expected number of INPUT events for this invocation, always set by new writers (including zero).
	// Replay/resume reject a completed or selected invocation with a missing/negative count or a
	// different committed INPUT count before running the harness. An incomplete trailing invocation
	// is skipped by completed replay. Count-less experimental start markers fail closed; truly
	// markerless legacy executions retain their existing reconstruction behavior.
	InputCount    *int64 `protobuf:"varint,3,opt,name=input_count,json=inputCount,proto3,oneof" json:"input_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStart) Reset() {
	*x = ExecutionStart{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStart) ProtoMessage() {}

func (x *ExecutionStart) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStart.ProtoReflect.Descriptor instead.
func (*ExecutionStart) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *ExecutionStart) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecutionStart) GetResumeFromSeq() int64 {
	if x != nil {
		return x.ResumeFromSeq
	}
	return 0
}

func (x *ExecutionStart) GetInputCount() int64 {
	if x != nil && x.InputCount != nil {
		return *x.InputCount
	}
	return 0
}

// Event is the shared journal/stream content unit; EXECUTION_START is emitted only by the host.
// Ordering (seq) and integrity (prev_hash /
// content_hash) are host-assigned and live on LogRecord — the harness, which does not know
// seq/prev, emits a hash-free Event, so there is no circular hashing. Streaming deltas are
// transport (see Delta in session.proto) and coalesce into the finalized event (§3).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"` // which execution/turn produced this event
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"` // §7: versions the body; replay survives schema skew
	Kind          EventKind              `protobuf:"varint,7,opt,name=kind,proto3,enum=agentsessions.v1.EventKind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Event_Message
	//	*Event_Model
	//	*Event_Tool
	//	*Event_Result
	//	*Event_Approval
	//	*Event_ApprovalResult
	//	*Event_Usage
	//	*Event_Lifecycle
	//	*Event_End
	//	*Event_Error
	//	*Event_ExecutionStart
	Body          isEvent_Body `protobuf_oneof:"body"`
	Actor         *IdentityRef `protobuf:"bytes,18,opt,name=actor,proto3" json:"actor,omitempty"` // emitter principal -> provenance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{19}
}

func (x *Event) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Event) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Event) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_KIND_UNSPECIFIED
}

func (x *Event) GetBody() isEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Body.(*Event_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Event) GetModel() *ModelCall {
	if x != nil {
		if x, ok := x.Body.(*Event_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *Event) GetTool() *ToolCall {
	if x != nil {
		if x, ok := x.Body.(*Event_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *Event) GetResult() *ToolResult {
	if x != nil {
		if x, ok := x.Body.(*Event_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Event) GetApproval() *ApprovalRequest {
	if x != nil {
		if x, ok := x.Body.(*Event_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *Event) GetApprovalResult() *ApprovalResult {
	if x != nil {
		if x, ok := x.Body.(*Event_ApprovalResult); ok {
			return x.ApprovalResult
		}
	}
	return nil
}

func (x *Event) GetUsage() *Usage {
	if x != nil {
		if x, ok := x.Body.(*Event_Usage); ok {
			return x.Usage
		}
	}
	return nil
}

func (x *Event) GetLifecycle() *Lifecycle {
	if x != nil {
		if x, ok := x.Body.(*Event_Lifecycle); ok {
			return x.Lifecycle
		}
	}
	return nil
}

func (x *Event) GetEnd() *HarnessEnd {
	if x != nil {
		if x, ok := x.Body.(*Event_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *Event) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Event) GetExecutionStart() *ExecutionStart {
	if x != nil {
		if x, ok := x.Body.(*Event_ExecutionStart); ok {
			return x.ExecutionStart
		}
	}
	return nil
}

func (x *Event) GetActor() *IdentityRef {
	if x != nil {
		return x.Actor
	}
	return nil
}

type isEvent_Body interface {
	isEvent_Body()
}

type Event_Message struct {
	Message *Message `protobuf:"bytes,8,opt,name=message,proto3,oneof"`
}

type Event_Model struct {
	Model *ModelCall `protobuf:"bytes,9,opt,name=model,proto3,oneof"`
}

type Event_Tool struct {
	Tool *ToolCall `protobuf:"bytes,10,opt,name=tool,proto3,oneof"`
}

type Event_Result struct {
	Result *ToolResult `protobuf:"bytes,11,opt,name=result,proto3,oneof"`
}

type Event_Approval struct {
	Approval *ApprovalRequest `protobuf:"bytes,12,opt,name=approval,proto3,oneof"`
}

type Event_ApprovalResult struct {
	ApprovalResult *ApprovalResult `protobuf:"bytes,13,opt,name=approval_result,json=approvalResult,proto3,oneof"`
}

type Event_Usage struct {
	Usage *Usage `protobuf:"bytes,14,opt,name=usage,proto3,oneof"`
}

type Event_Lifecycle struct {
	Lifecycle *Lifecycle `protobuf:"bytes,15,opt,name=lifecycle,proto3,oneof"`
}

type Event_End struct {
	End *HarnessEnd `protobuf:"bytes,16,opt,name=end,proto3,oneof"`
}

type Event_Error struct {
	Error *Error `protobuf:"bytes,17,opt,name=error,proto3,oneof"`
}

type Event_ExecutionStart struct {
	ExecutionStart *ExecutionStart `protobuf:"bytes,19,opt,name=execution_start,json=executionStart,proto3,oneof"`
}

func (*Event_Message) isEvent_Body() {}

func (*Event_Model) isEvent_Body() {}

func (*Event_Tool) isEvent_Body() {}

func (*Event_Result) isEvent_Body() {}

func (*Event_Approval) isEvent_Body() {}

func (*Event_ApprovalResult) isEvent_Body() {}

func (*Event_Usage) isEvent_Body() {}

func (*Event_Lifecycle) isEvent_Body() {}

func (*Event_End) isEvent_Body() {}

func (*Event_Error) isEvent_Body() {}

func (*Event_ExecutionStart) isEvent_Body() {}

// LogRecord is the host's durable, ordered wrapper around an Event. The host assigns seq,
// links the hash-chain (content_hash = H(prev_hash || seq || canonical(event)); at a fork
// child.first.prev_hash = parent@R.content_hash), and records the incarnation fence token.
// Externalized payloads (FilePart.uri, ReasoningPart.opaque_uri, ToolResult.output_uri)
// carry their own content digest so the chain covers them by reference.
type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	PrevHash      string                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Fence         int64                  `protobuf:"varint,4,opt,name=fence,proto3" json:"fence,omitempty"`
	Event         *Event                 `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{20}
}

func (x *LogRecord) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogRecord) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *LogRecord) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *LogRecord) GetFence() int64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *LogRecord) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x10agentsessions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xe6\x01\n" +
	"\x10ResourceMetadata\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\xe5\x01\n" +
	"\x04Part\x120\n" +
	"\x04text\x18\x01 \x01(\v2\x1a.agentsessions.v1.TextPartH\x00R\x04text\x120\n" +
	"\x04file\x18\x02 \x01(\v2\x1a.agentsessions.v1.FilePartH\x00R\x04file\x120\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.agentsessions.v1.DataPartH\x00R\x04data\x12?\n" +
	"\treasoning\x18\x04 \x01(\v2\x1f.agentsessions.v1.ReasoningPartH\x00R\treasoningB\x06\n" +
	"\x04part\"\x1e\n" +
	"\bTextPart\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x80\x01\n" +
	"\bFilePart\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x16\n" +
	"\x05bytes\x18\x02 \x01(\fH\x00R\x05bytes\x12\x12\n" +
	"\x03uri\x18\x03 \x01(\tH\x00R\x03uri\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digestB\b\n" +
	"\x06source\"7\n" +
	"\bDataPart\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\"\xc7\x02\n" +
	"\rReasoningPart\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\fopaque_bytes\x18\x03 \x01(\fH\x00R\vopaqueBytes\x12\x1f\n" +
	"\n" +
	"opaque_uri\x18\x04 \x01(\tH\x00R\topaqueUri\x120\n" +
	"\asummary\x18\x05 \x03(\v2\x16.agentsessions.v1.PartR\asummary\x12\x17\n" +
	"\aitem_id\x18\x06 \x01(\tR\x06itemId\x12\x18\n" +
	"\aordinal\x18\a \x01(\x05R\aordinal\x12%\n" +
	"\x0evalidity_scope\x18\b \x01(\tR\rvalidityScope\x12#\n" +
	"\ropaque_digest\x18\t \x01(\tR\fopaqueDigestB\b\n" +
	"\x06opaque\"K\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12,\n" +
	"\x05parts\x18\x02 \x03(\v2\x16.agentsessions.v1.PartR\x05parts\"]\n" +
	"\vIdentityRef\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\"\xd5\x01\n" +
	"\x06Origin\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12H\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2(.agentsessions.v1.Origin.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x02\n" +
	"\tModelCall\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12?\n" +
	"\x06params\x18\x02 \x03(\v2'.agentsessions.v1.ModelCall.ParamsEntryR\x06params\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x03 \x01(\tR\tinputHash\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x125\n" +
	"\bmessages\x18\x05 \x03(\v2\x19.agentsessions.v1.MessageR\bmessages\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x05Usage\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x02 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\"\xbf\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x129\n" +
	"\tmediation\x18\x04 \x01(\x0e2\x1b.agentsessions.v1.MediationR\tmediation\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xc2\x01\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x06output\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06output\x12\x1d\n" +
	"\n" +
	"output_uri\x18\x03 \x01(\tR\toutputUri\x12#\n" +
	"\routput_digest\x18\x06 \x01(\tR\foutputDigest\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"K\n" +
	"\x0fApprovalRequest\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"f\n" +
	"\x0eApprovalResult\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"=\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"Q\n" +
	"\n" +
	"HarnessEnd\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12-\n" +
	"\x05error\x18\x02 \x01(\v2\x17.agentsessions.v1.ErrorR\x05error\"\x99\x03\n" +
	"\tLifecycle\x124\n" +
	"\x04kind\x18\x01 \x01(\x0e2 .agentsessions.v1.Lifecycle.KindR\x04kind\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12%\n" +
	"\x0esnapshot_local\x18\x03 \x01(\tR\rsnapshotLocal\x122\n" +
	"\x15snapshot_external_uri\x18\x04 \x01(\tR\x13snapshotExternalUri\x12'\n" +
	"\x0fsnapshot_memory\x18\x05 \x01(\bR\x0esnapshotMemory\x12'\n" +
	"\x0fsnapshot_sealed\x18\x06 \x01(\bR\x0esnapshotSealed\"\x90\x01\n" +
	"\x04Kind\x12\x19\n" +
	"\x15LIFECYCLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LIFECYCLE_SUSPEND\x10\x01\x12\x14\n" +
	"\x10LIFECYCLE_RESUME\x10\x02\x12\x12\n" +
	"\x0eLIFECYCLE_FORK\x10\x03\x12\x16\n" +
	"\x12LIFECYCLE_BASELINE\x10\x04\x12\x14\n" +
	"\x10LIFECYCLE_CANCEL\x10\x05\"\x86\x01\n" +
	"\x0eExecutionStart\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12&\n" +
	"\x0fresume_from_seq\x18\x02 \x01(\x03R\rresumeFromSeq\x12$\n" +
	"\vinput_count\x18\x03 \x01(\x03H\x00R\n" +
	"inputCount\x88\x01\x01B\x0e\n" +
	"\f_input_count\"\xff\x06\n" +
	"\x05Event\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\x05R\rschemaVersion\x12/\n" +
	"\x04kind\x18\a \x01(\x0e2\x1b.agentsessions.v1.EventKindR\x04kind\x125\n" +
	"\amessage\x18\b \x01(\v2\x19.agentsessions.v1.MessageH\x00R\amessage\x123\n" +
	"\x05model\x18\t \x01(\v2\x1b.agentsessions.v1.ModelCallH\x00R\x05model\x120\n" +
	"\x04tool\x18\n" +
	" \x01(\v2\x1a.agentsessions.v1.ToolCallH\x00R\x04tool\x126\n" +
	"\x06result\x18\v \x01(\v2\x1c.agentsessions.v1.ToolResultH\x00R\x06result\x12?\n" +
	"\bapproval\x18\f \x01(\v2!.agentsessions.v1.ApprovalRequestH\x00R\bapproval\x12K\n" +
	"\x0fapproval_result\x18\r \x01(\v2 .agentsessions.v1.ApprovalResultH\x00R\x0eapprovalResult\x12/\n" +
	"\x05usage\x18\x0e \x01(\v2\x17.agentsessions.v1.UsageH\x00R\x05usage\x12;\n" +
	"\tlifecycle\x18\x0f \x01(\v2\x1b.agentsessions.v1.LifecycleH\x00R\tlifecycle\x120\n" +
	"\x03end\x18\x10 \x01(\v2\x1c.agentsessions.v1.HarnessEndH\x00R\x03end\x12/\n" +
	"\x05error\x18\x11 \x01(\v2\x17.agentsessions.v1.ErrorH\x00R\x05error\x12K\n" +
	"\x0fexecution_start\x18\x13 \x01(\v2 .agentsessions.v1.ExecutionStartH\x00R\x0eexecutionStart\x123\n" +
	"\x05actor\x18\x12 \x01(\v2\x1d.agentsessions.v1.IdentityRefR\x05actorB\x06\n" +
	"\x04bodyJ\x04\b\x01\x10\x02J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\xa2\x01\n" +
	"\tLogRecord\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\tR\bprevHash\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x14\n" +
	"\x05fence\x18\x04 \x01(\x03R\x05fence\x12-\n" +
	"\x05event\x18\x05 \x01(\v2\x17.agentsessions.v1.EventR\x05event*\x8d\x01\n" +
	"\tMediation\x12\x19\n" +
	"\x15MEDIATION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMEDIATION_IN_HARNESS_REPORTED\x10\x01\x12!\n" +
	"\x1dMEDIATION_CONTROLLER_MEDIATED\x10\x02\x12\x1f\n" +
	"\x1bMEDIATION_REQUIRES_APPROVAL\x10\x03*\xa4\x02\n" +
	"\tEventKind\x12\x1a\n" +
	"\x16EVENT_KIND_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vEVENT_INPUT\x10\x01\x12\x14\n" +
	"\x10EVENT_MODEL_CALL\x10\x02\x12\x10\n" +
	"\fEVENT_OUTPUT\x10\x03\x12\x13\n" +
	"\x0fEVENT_TOOL_CALL\x10\x04\x12\x15\n" +
	"\x11EVENT_TOOL_RESULT\x10\x05\x12\x1a\n" +
	"\x16EVENT_APPROVAL_REQUEST\x10\x06\x12\x19\n" +
	"\x15EVENT_APPROVAL_RESULT\x10\a\x12\x0f\n" +
	"\vEVENT_USAGE\x10\b\x12\x13\n" +
	"\x0fEVENT_LIFECYCLE\x10\t\x12\r\n" +
	"\tEVENT_END\x10\n" +
	"\x12\x0f\n" +
	"\vEVENT_ERROR\x10\v\x12\x19\n" +
	"\x15EVENT_EXECUTION_START\x10\fB<Z:github.com/aramase/agentsessions/api/genpb;agentsessionsv1b\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_common_proto_goTypes = []any{
	(Mediation)(0),                // 0: agentsessions.v1.Mediation
	(EventKind)(0),                // 1: agentsessions.v1.EventKind
	(Lifecycle_Kind)(0),           // 2: agentsessions.v1.Lifecycle.Kind
	(*ResourceMetadata)(nil),      // 3: agentsessions.v1.ResourceMetadata
	(*Part)(nil),                  // 4: agentsessions.v1.Part
	(*TextPart)(nil),              // 5: agentsessions.v1.TextPart
	(*FilePart)(nil),              // 6: agentsessions.v1.FilePart
	(*DataPart)(nil),              // 7: agentsessions.v1.DataPart
	(*ReasoningPart)(nil),         // 8: agentsessions.v1.ReasoningPart
	(*Message)(nil),               // 9: agentsessions.v1.Message
	(*IdentityRef)(nil),           // 10: agentsessions.v1.IdentityRef
	(*Origin)(nil),                // 11: agentsessions.v1.Origin
	(*ModelCall)(nil),             // 12: agentsessions.v1.ModelCall
	(*Usage)(nil),                 // 13: agentsessions.v1.Usage
	(*ToolCall)(nil),              // 14: agentsessions.v1.ToolCall
	(*ToolResult)(nil),            // 15: agentsessions.v1.ToolResult
	(*ApprovalRequest)(nil),       // 16: agentsessions.v1.ApprovalRequest
	(*ApprovalResult)(nil),        // 17: agentsessions.v1.ApprovalResult
	(*Error)(nil),                 // 18: agentsessions.v1.Error
	(*HarnessEnd)(nil),            // 19: agentsessions.v1.HarnessEnd
	(*Lifecycle)(nil),             // 20: agentsessions.v1.Lifecycle
	(*ExecutionStart)(nil),        // 21: agentsessions.v1.ExecutionStart
	(*Event)(nil),                 // 22: agentsessions.v1.Event
	(*LogRecord)(nil),             // 23: agentsessions.v1.LogRecord
	nil,                           // 24: agentsessions.v1.Origin.AttributesEntry
	nil,                           // 25: agentsessions.v1.ModelCall.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 27: google.protobuf.Struct
}
var file_common_proto_depIdxs = []int32{
	26, // 0: agentsessions.v1.ResourceMetadata.create_time:type_name -> google.protobuf.Timestamp
	26, // 1: agentsessions.v1.ResourceMetadata.update_time:type_name -> google.protobuf.Timestamp
	5,  // 2: agentsessions.v1.Part.text:type_name -> agentsessions.v1.TextPart
	6,  // 3: agentsessions.v1.Part.file:type_name -> agentsessions.v1.FilePart
	7,  // 4: agentsessions.v1.Part.data:type_name -> agentsessions.v1.DataPart
	8,  // 5: agentsessions.v1.Part.reasoning:type_name -> agentsessions.v1.ReasoningPart
	27, // 6: agentsessions.v1.DataPart.data:type_name -> google.protobuf.Struct
	4,  // 7: agentsessions.v1.ReasoningPart.summary:type_name -> agentsessions.v1.Part
	4,  // 8: agentsessions.v1.Message.parts:type_name -> agentsessions.v1.Part
	24, // 9: agentsessions.v1.Origin.attributes:type_name -> agentsessions.v1.Origin.AttributesEntry
	25, // 10: agentsessions.v1.ModelCall.params:type_name -> agentsessions.v1.ModelCall.ParamsEntry
	9,  // 11: agentsessions.v1.ModelCall.messages:type_name -> agentsessions.v1.Message
	27, // 12: agentsessions.v1.ToolCall.args:type_name -> google.protobuf.Struct
	0,  // 13: agentsessions.v1.ToolCall.mediation:type_name -> agentsessions.v1.Mediation
	27, // 14: agentsessions.v1.ToolResult.output:type_name -> google.protobuf.Struct
	18, // 15: agentsessions.v1.HarnessEnd.error:type_name -> agentsessions.v1.Error
	2,  // 16: agentsessions.v1.Lifecycle.kind:type_name -> agentsessions.v1.Lifecycle.Kind
	26, // 17: agentsessions.v1.Event.ts:type_name -> google.protobuf.Timestamp
	1,  // 18: agentsessions.v1.Event.kind:type_name -> agentsessions.v1.EventKind
	9,  // 19: agentsessions.v1.Event.message:type_name -> agentsessions.v1.Message
	12, // 20: agentsessions.v1.Event.model:type_name -> agentsessions.v1.ModelCall
	14, // 21: agentsessions.v1.Event.tool:type_name -> agentsessions.v1.ToolCall
	15, // 22: agentsessions.v1.Event.result:type_name -> agentsessions.v1.ToolResult
	16, // 23: agentsessions.v1.Event.approval:type_name -> agentsessions.v1.ApprovalRequest
	17, // 24: agentsessions.v1.Event.approval_result:type_name -> agentsessions.v1.ApprovalResult
	13, // 25: agentsessions.v1.Event.usage:type_name -> agentsessions.v1.Usage
	20, // 26: agentsessions.v1.Event.lifecycle:type_name -> agentsessions.v1.Lifecycle
	19, // 27: agentsessions.v1.Event.end:type_name -> agentsessions.v1.HarnessEnd
	18, // 28: agentsessions.v1.Event.error:type_name -> agentsessions.v1.Error
	21, // 29: agentsessions.v1.Event.execution_start:type_name -> agentsessions.v1.ExecutionStart
	10, // 30: agentsessions.v1.Event.actor:type_name -> agentsessions.v1.IdentityRef
	22, // 31: agentsessions.v1.LogRecord.event:type_name -> agentsessions.v1.Event
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[1].OneofWrappers = []any{
		(*Part_Text)(nil),
		(*Part_File)(nil),
		(*Part_Data)(nil),
		(*Part_Reasoning)(nil),
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{
		(*FilePart_Bytes)(nil),
		(*FilePart_Uri)(nil),
	}
	file_common_proto_msgTypes[5].OneofWrappers = []any{
		(*ReasoningPart_OpaqueBytes)(nil),
		(*ReasoningPart_OpaqueUri)(nil),
	}
	file_common_proto_msgTypes[18].OneofWrappers = []any{}
	file_common_proto_msgTypes[19].OneofWrappers = []any{
		(*Event_Message)(nil),
		(*Event_Model)(nil),
		(*Event_Tool)(nil),
		(*Event_Result)(nil),
		(*Event_Approval)(nil),
		(*Event_ApprovalResult)(nil),
		(*Event_Usage)(nil),
		(*Event_Lifecycle)(nil),
		(*Event_End)(nil),
		(*Event_Error)(nil),
		(*Event_ExecutionStart)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
