// The Harness BYOH SPI: the contract between the host and an agent implementation.
//
// A Microsoft Agent Framework (MAF) agent, a GitHub Copilot agent, or a custom agent
// implements it via a thin adapter. The host drives one execution per Connect stream;
// the harness streams typed Events terminated by one EVENT_END. Beyond plain streaming, it
// adds tool-call / approval mediation, per-call usage, and capability declaration.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: harness.proto

package agentsessionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resumability declares how a harness survives suspend/resume/fork. The host matches
// this against a runtime's RuntimeCapabilities.
type Resumability int32

const (
	Resumability_RESUMABILITY_UNSPECIFIED              Resumability = 0
	Resumability_RESUMABILITY_STATELESS_REPLAY         Resumability = 1 // default: rehydrate from history; any runtime
	Resumability_RESUMABILITY_REQUIRES_MEMORY_SNAPSHOT Resumability = 2 // needs a memory-snapshot-capable runtime
)

// Enum value maps for Resumability.
var (
	Resumability_name = map[int32]string{
		0: "RESUMABILITY_UNSPECIFIED",
		1: "RESUMABILITY_STATELESS_REPLAY",
		2: "RESUMABILITY_REQUIRES_MEMORY_SNAPSHOT",
	}
	Resumability_value = map[string]int32{
		"RESUMABILITY_UNSPECIFIED":              0,
		"RESUMABILITY_STATELESS_REPLAY":         1,
		"RESUMABILITY_REQUIRES_MEMORY_SNAPSHOT": 2,
	}
)

func (x Resumability) Enum() *Resumability {
	p := new(Resumability)
	*p = x
	return p
}

func (x Resumability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Resumability) Descriptor() protoreflect.EnumDescriptor {
	return file_harness_proto_enumTypes[0].Descriptor()
}

func (Resumability) Type() protoreflect.EnumType {
	return &file_harness_proto_enumTypes[0]
}

func (x Resumability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Resumability.Descriptor instead.
func (Resumability) EnumDescriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{0}
}

type Capabilities struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Resumability Resumability           `protobuf:"varint,1,opt,name=resumability,proto3,enum=agentsessions.v1.Resumability" json:"resumability,omitempty"`
	ForkSafe     bool                   `protobuf:"varint,2,opt,name=fork_safe,json=forkSafe,proto3" json:"fork_safe,omitempty"` // no un-replayable side effects mid-turn
	RequiresGpu  bool                   `protobuf:"varint,3,opt,name=requires_gpu,json=requiresGpu,proto3" json:"requires_gpu,omitempty"`
	Streaming    bool                   `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// reasoning_replay: harness replays opaque reasoning parts verbatim via the provider
	// stateless path; keeps reasoning on STATELESS_REPLAY (no memory-snapshot edge).
	ReasoningReplay bool `protobuf:"varint,5,opt,name=reasoning_replay,json=reasoningReplay,proto3" json:"reasoning_replay,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{0}
}

func (x *Capabilities) GetResumability() Resumability {
	if x != nil {
		return x.Resumability
	}
	return Resumability_RESUMABILITY_UNSPECIFIED
}

func (x *Capabilities) GetForkSafe() bool {
	if x != nil {
		return x.ForkSafe
	}
	return false
}

func (x *Capabilities) GetRequiresGpu() bool {
	if x != nil {
		return x.RequiresGpu
	}
	return false
}

func (x *Capabilities) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *Capabilities) GetReasoningReplay() bool {
	if x != nil {
		return x.ReasoningReplay
	}
	return false
}

type ToolSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Mediation     Mediation              `protobuf:"varint,3,opt,name=mediation,proto3,enum=agentsessions.v1.Mediation" json:"mediation,omitempty"` // default mediation for this tool
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSpec) Reset() {
	*x = ToolSpec{}
	mi := &file_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSpec) ProtoMessage() {}

func (x *ToolSpec) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSpec.ProtoReflect.Descriptor instead.
func (*ToolSpec) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{1}
}

func (x *ToolSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSpec) GetMediation() Mediation {
	if x != nil {
		return x.Mediation
	}
	return Mediation_MEDIATION_UNSPECIFIED
}

type HarnessDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Models        []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"` // model-agnostic: supported/required model ids
	Tools         []*ToolSpec            `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Capabilities  *Capabilities          `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessDescriptor) Reset() {
	*x = HarnessDescriptor{}
	mi := &file_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessDescriptor) ProtoMessage() {}

func (x *HarnessDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessDescriptor.ProtoReflect.Descriptor instead.
func (*HarnessDescriptor) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{2}
}

func (x *HarnessDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HarnessDescriptor) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *HarnessDescriptor) GetTools() []*ToolSpec {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *HarnessDescriptor) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{3}
}

// IdentityContext carries the principal and signals whether the harness may mint
// scoped, delegated tokens (Transaction Tokens) via the host for tool calls.
type IdentityContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *IdentityRef           `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	CanMintTokens bool                   `protobuf:"varint,2,opt,name=can_mint_tokens,json=canMintTokens,proto3" json:"can_mint_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityContext) Reset() {
	*x = IdentityContext{}
	mi := &file_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityContext) ProtoMessage() {}

func (x *IdentityContext) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityContext.ProtoReflect.Descriptor instead.
func (*IdentityContext) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityContext) GetPrincipal() *IdentityRef {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *IdentityContext) GetCanMintTokens() bool {
	if x != nil {
		return x.CanMintTokens
	}
	return false
}

// Start begins one execution. History is pushed here (pull-by-range is a later
// addition); it is empty when the sandbox was memory-restored.
type Start struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Config  []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	History []*Event               `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	// Invocation input messages. Controller replay and interrupted recovery restore the original
	// messages from the journal; empty inputs describe an intentionally inputless invocation.
	Inputs        []*Message       `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Identity      *IdentityContext `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	ResumeFromSeq int64            `protobuf:"varint,5,opt,name=resume_from_seq,json=resumeFromSeq,proto3" json:"resume_from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Start) Reset() {
	*x = Start{}
	mi := &file_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Start) ProtoMessage() {}

func (x *Start) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Start.ProtoReflect.Descriptor instead.
func (*Start) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{5}
}

func (x *Start) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Start) GetHistory() []*Event {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Start) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Start) GetIdentity() *IdentityContext {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Start) GetResumeFromSeq() int64 {
	if x != nil {
		return x.ResumeFromSeq
	}
	return 0
}

type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"` // USER | TIMEOUT | INTERNAL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_harness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{6}
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ControllerFrame is sent by the host to the harness during an execution.
type ControllerFrame struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Session     string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ExecutionId string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Types that are valid to be assigned to Frame:
	//
	//	*ControllerFrame_Start
	//	*ControllerFrame_Cancel
	//	*ControllerFrame_Approval
	//	*ControllerFrame_Tool
	//	*ControllerFrame_Model
	Frame         isControllerFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerFrame) Reset() {
	*x = ControllerFrame{}
	mi := &file_harness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerFrame) ProtoMessage() {}

func (x *ControllerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerFrame.ProtoReflect.Descriptor instead.
func (*ControllerFrame) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{7}
}

func (x *ControllerFrame) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ControllerFrame) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ControllerFrame) GetFrame() isControllerFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ControllerFrame) GetStart() *Start {
	if x != nil {
		if x, ok := x.Frame.(*ControllerFrame_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ControllerFrame) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Frame.(*ControllerFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *ControllerFrame) GetApproval() *ApprovalResult {
	if x != nil {
		if x, ok := x.Frame.(*ControllerFrame_Approval); ok {
			return x.Approval
		}
	}
	return nil
}

func (x *ControllerFrame) GetTool() *ToolResult {
	if x != nil {
		if x, ok := x.Frame.(*ControllerFrame_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *ControllerFrame) GetModel() *ModelResult {
	if x != nil {
		if x, ok := x.Frame.(*ControllerFrame_Model); ok {
			return x.Model
		}
	}
	return nil
}

type isControllerFrame_Frame interface {
	isControllerFrame_Frame()
}

type ControllerFrame_Start struct {
	Start *Start `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type ControllerFrame_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type ControllerFrame_Approval struct {
	Approval *ApprovalResult `protobuf:"bytes,5,opt,name=approval,proto3,oneof"` // response to an EVENT_APPROVAL_REQUEST
}

type ControllerFrame_Tool struct {
	Tool *ToolResult `protobuf:"bytes,6,opt,name=tool,proto3,oneof"` // result for a CONTROLLER_MEDIATED tool call
}

type ControllerFrame_Model struct {
	Model *ModelResult `protobuf:"bytes,7,opt,name=model,proto3,oneof"` // served completion for a mediated/replayed model call
}

func (*ControllerFrame_Start) isControllerFrame_Frame() {}

func (*ControllerFrame_Cancel) isControllerFrame_Frame() {}

func (*ControllerFrame_Approval) isControllerFrame_Frame() {}

func (*ControllerFrame_Tool) isControllerFrame_Frame() {}

func (*ControllerFrame_Model) isControllerFrame_Frame() {}

// ModelResult is a model completion served to the harness (live invocation or replay).
// The Message carries text + opaque reasoning parts, recorded verbatim for continuity.
type ModelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	ModelCallId   string                 `protobuf:"bytes,3,opt,name=model_call_id,json=modelCallId,proto3" json:"model_call_id,omitempty"` // correlates to the emitted ModelCall.id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelResult) Reset() {
	*x = ModelResult{}
	mi := &file_harness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelResult) ProtoMessage() {}

func (x *ModelResult) ProtoReflect() protoreflect.Message {
	mi := &file_harness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelResult.ProtoReflect.Descriptor instead.
func (*ModelResult) Descriptor() ([]byte, []int) {
	return file_harness_proto_rawDescGZIP(), []int{8}
}

func (x *ModelResult) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ModelResult) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ModelResult) GetModelCallId() string {
	if x != nil {
		return x.ModelCallId
	}
	return ""
}

var File_harness_proto protoreflect.FileDescriptor

const file_harness_proto_rawDesc = "" +
	"\n" +
	"\rharness.proto\x12\x10agentsessions.v1\x1a\fcommon.proto\"\xdb\x01\n" +
	"\fCapabilities\x12B\n" +
	"\fresumability\x18\x01 \x01(\x0e2\x1e.agentsessions.v1.ResumabilityR\fresumability\x12\x1b\n" +
	"\tfork_safe\x18\x02 \x01(\bR\bforkSafe\x12!\n" +
	"\frequires_gpu\x18\x03 \x01(\bR\vrequiresGpu\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12)\n" +
	"\x10reasoning_replay\x18\x05 \x01(\bR\x0freasoningReplay\"{\n" +
	"\bToolSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\tmediation\x18\x03 \x01(\x0e2\x1b.agentsessions.v1.MediationR\tmediation\"\xb1\x01\n" +
	"\x11HarnessDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x120\n" +
	"\x05tools\x18\x03 \x03(\v2\x1a.agentsessions.v1.ToolSpecR\x05tools\x12B\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x1e.agentsessions.v1.CapabilitiesR\fcapabilities\"\x11\n" +
	"\x0fDescribeRequest\"v\n" +
	"\x0fIdentityContext\x12;\n" +
	"\tprincipal\x18\x01 \x01(\v2\x1d.agentsessions.v1.IdentityRefR\tprincipal\x12&\n" +
	"\x0fcan_mint_tokens\x18\x02 \x01(\bR\rcanMintTokens\"\xec\x01\n" +
	"\x05Start\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x121\n" +
	"\ahistory\x18\x02 \x03(\v2\x17.agentsessions.v1.EventR\ahistory\x121\n" +
	"\x06inputs\x18\x03 \x03(\v2\x19.agentsessions.v1.MessageR\x06inputs\x12=\n" +
	"\bidentity\x18\x04 \x01(\v2!.agentsessions.v1.IdentityContextR\bidentity\x12&\n" +
	"\x0fresume_from_seq\x18\x05 \x01(\x03R\rresumeFromSeq\" \n" +
	"\x06Cancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xe7\x02\n" +
	"\x0fControllerFrame\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12/\n" +
	"\x05start\x18\x03 \x01(\v2\x17.agentsessions.v1.StartH\x00R\x05start\x122\n" +
	"\x06cancel\x18\x04 \x01(\v2\x18.agentsessions.v1.CancelH\x00R\x06cancel\x12>\n" +
	"\bapproval\x18\x05 \x01(\v2 .agentsessions.v1.ApprovalResultH\x00R\bapproval\x122\n" +
	"\x04tool\x18\x06 \x01(\v2\x1c.agentsessions.v1.ToolResultH\x00R\x04tool\x125\n" +
	"\x05model\x18\a \x01(\v2\x1d.agentsessions.v1.ModelResultH\x00R\x05modelB\a\n" +
	"\x05frame\"\x95\x01\n" +
	"\vModelResult\x123\n" +
	"\amessage\x18\x01 \x01(\v2\x19.agentsessions.v1.MessageR\amessage\x12-\n" +
	"\x05usage\x18\x02 \x01(\v2\x17.agentsessions.v1.UsageR\x05usage\x12\"\n" +
	"\rmodel_call_id\x18\x03 \x01(\tR\vmodelCallId*z\n" +
	"\fResumability\x12\x1c\n" +
	"\x18RESUMABILITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRESUMABILITY_STATELESS_REPLAY\x10\x01\x12)\n" +
	"%RESUMABILITY_REQUIRES_MEMORY_SNAPSHOT\x10\x022\xa8\x01\n" +
	"\aHarness\x12R\n" +
	"\bDescribe\x12!.agentsessions.v1.DescribeRequest\x1a#.agentsessions.v1.HarnessDescriptor\x12I\n" +
	"\aConnect\x12!.agentsessions.v1.ControllerFrame\x1a\x17.agentsessions.v1.Event(\x010\x01B<Z:github.com/aramase/agentsessions/api/genpb;agentsessionsv1b\x06proto3"

var (
	file_harness_proto_rawDescOnce sync.Once
	file_harness_proto_rawDescData []byte
)

func file_harness_proto_rawDescGZIP() []byte {
	file_harness_proto_rawDescOnce.Do(func() {
		file_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)))
	})
	return file_harness_proto_rawDescData
}

var file_harness_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_harness_proto_goTypes = []any{
	(Resumability)(0),         // 0: agentsessions.v1.Resumability
	(*Capabilities)(nil),      // 1: agentsessions.v1.Capabilities
	(*ToolSpec)(nil),          // 2: agentsessions.v1.ToolSpec
	(*HarnessDescriptor)(nil), // 3: agentsessions.v1.HarnessDescriptor
	(*DescribeRequest)(nil),   // 4: agentsessions.v1.DescribeRequest
	(*IdentityContext)(nil),   // 5: agentsessions.v1.IdentityContext
	(*Start)(nil),             // 6: agentsessions.v1.Start
	(*Cancel)(nil),            // 7: agentsessions.v1.Cancel
	(*ControllerFrame)(nil),   // 8: agentsessions.v1.ControllerFrame
	(*ModelResult)(nil),       // 9: agentsessions.v1.ModelResult
	(Mediation)(0),            // 10: agentsessions.v1.Mediation
	(*IdentityRef)(nil),       // 11: agentsessions.v1.IdentityRef
	(*Event)(nil),             // 12: agentsessions.v1.Event
	(*Message)(nil),           // 13: agentsessions.v1.Message
	(*ApprovalResult)(nil),    // 14: agentsessions.v1.ApprovalResult
	(*ToolResult)(nil),        // 15: agentsessions.v1.ToolResult
	(*Usage)(nil),             // 16: agentsessions.v1.Usage
}
var file_harness_proto_depIdxs = []int32{
	0,  // 0: agentsessions.v1.Capabilities.resumability:type_name -> agentsessions.v1.Resumability
	10, // 1: agentsessions.v1.ToolSpec.mediation:type_name -> agentsessions.v1.Mediation
	2,  // 2: agentsessions.v1.HarnessDescriptor.tools:type_name -> agentsessions.v1.ToolSpec
	1,  // 3: agentsessions.v1.HarnessDescriptor.capabilities:type_name -> agentsessions.v1.Capabilities
	11, // 4: agentsessions.v1.IdentityContext.principal:type_name -> agentsessions.v1.IdentityRef
	12, // 5: agentsessions.v1.Start.history:type_name -> agentsessions.v1.Event
	13, // 6: agentsessions.v1.Start.inputs:type_name -> agentsessions.v1.Message
	5,  // 7: agentsessions.v1.Start.identity:type_name -> agentsessions.v1.IdentityContext
	6,  // 8: agentsessions.v1.ControllerFrame.start:type_name -> agentsessions.v1.Start
	7,  // 9: agentsessions.v1.ControllerFrame.cancel:type_name -> agentsessions.v1.Cancel
	14, // 10: agentsessions.v1.ControllerFrame.approval:type_name -> agentsessions.v1.ApprovalResult
	15, // 11: agentsessions.v1.ControllerFrame.tool:type_name -> agentsessions.v1.ToolResult
	9,  // 12: agentsessions.v1.ControllerFrame.model:type_name -> agentsessions.v1.ModelResult
	13, // 13: agentsessions.v1.ModelResult.message:type_name -> agentsessions.v1.Message
	16, // 14: agentsessions.v1.ModelResult.usage:type_name -> agentsessions.v1.Usage
	4,  // 15: agentsessions.v1.Harness.Describe:input_type -> agentsessions.v1.DescribeRequest
	8,  // 16: agentsessions.v1.Harness.Connect:input_type -> agentsessions.v1.ControllerFrame
	3,  // 17: agentsessions.v1.Harness.Describe:output_type -> agentsessions.v1.HarnessDescriptor
	12, // 18: agentsessions.v1.Harness.Connect:output_type -> agentsessions.v1.Event
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_harness_proto_init() }
func file_harness_proto_init() {
	if File_harness_proto != nil {
		return
	}
	file_common_proto_init()
	file_harness_proto_msgTypes[7].OneofWrappers = []any{
		(*ControllerFrame_Start)(nil),
		(*ControllerFrame_Cancel)(nil),
		(*ControllerFrame_Approval)(nil),
		(*ControllerFrame_Tool)(nil),
		(*ControllerFrame_Model)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_proto_rawDesc), len(file_harness_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_proto_goTypes,
		DependencyIndexes: file_harness_proto_depIdxs,
		EnumInfos:         file_harness_proto_enumTypes,
		MessageInfos:      file_harness_proto_msgTypes,
	}.Build()
	File_harness_proto = out.File
	file_harness_proto_goTypes = nil
	file_harness_proto_depIdxs = nil
}
